name: horock
channels: !!python/tuple
- menpo
- defaults
dependencies:
- bzip2=1.0.6=3
- menpo::opencv3=3.1.0=py35_0
- jpeg=9b=0
- libpng=1.6.27=0
- menpo::boost=1.59.0=py35_0
- menpo::dlib=19.4=py35_0
- conda-forge::tbb
- mkl=2017.0.3=0
- numpy=1.13.0=py35_0
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- python=3.5.3=1
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - absl-py==0.7.0
  - astor==0.7.1
  - astroid==2.1.0
  - backports.weakref==1.0rc1
  - bleach==1.5.0
  - certifi==2018.11.29
  - Click==7.0
  - cloudpickle==0.7.0
  - cmake==3.13.3
  - cycler==0.10.0
  - dask==1.1.1
  - decorator==4.3.2
  - dlib==19.16.0
  - face-recognition==1.2.3
  - face-recognition-models==0.3.0
  - ffmpy==0.2.2
  - gast==0.2.2
  - grpcio==1.18.0
  - h5py==2.8.0
  - html5lib==0.9999999
  - imutils==0.4.3
  - isort==4.3.4
  - Keras==2.2.4
  - Keras-Applications==1.0.7
  - Keras-Preprocessing==1.0.9
  - kiwisolver==1.0.1
  - lazy-object-proxy==1.3.1
  - markdown==3.0.1
  - matplotlib==2.2.2
  - mccabe==0.6.1
  - networkx==2.2
  - numpy==1.15.4
  - nvidia-ml-py3==7.352.0
  - opencv-python==4.0.0.21
  - pathlib==1.0.1
  - Pillow==5.4.1
  - protobuf==3.6.1
  - psutil==5.5.0
  - pylint==2.2.2
  - pyparsing==2.3.1
  - python-dateutil==2.8.0
  - pytz==2018.9
  - PyWavelets==1.0.1
  - PyYAML==3.13
  - scandir==1.7
  - scikit-image==0.14.2
  - scikit-learn==0.20.2
  - scipy==1.2.0
  - six==1.12.0
  - tensorboard==1.11.0
  - tensorflow-gpu==1.11.0
  - termcolor==1.1.0
  - toolz==0.9.0
  - tqdm==4.30.0
  - typed-ast==1.2.0
  - werkzeug==0.14.1
  - wrapt==1.11.1
